
version: 2

models:

  # -------------------------------------------------------
  # STAGING LAYER
  # -------------------------------------------------------
  - name: stg_prices
    description: >
      Daily historical stock prices (OHLCV) sourced from Yahoo Finance.
    columns:
      - name: date
        description: "Trading day date."
        tests:
          - not_null

      - name: ticker
        description: "Stock ticker symbol."
        tests:
          - not_null
          - relationships:
              to: ref('stg_metadata')
              field: ticker

      - name: close
        description: "Adjusted closing price."

  - name: stg_metadata
    description: >
      Company descriptive metadata including sector and industry classification.
    columns:
      - name: ticker
        description: "Primary key: Unique identifier for each company."
        tests:
          - not_null
          - unique

      - name: company_name
        description: "Official company name."

      - name: sector
        description: "GICS sector classification."

      - name: industry
        description: "GICS industry classification."

  # -------------------------------------------------------
  # INTERMEDIATE LAYER
  # -------------------------------------------------------
  - name: i_returns
    description: >
      Daily returns calculated from adjusted closing prices.
    columns:
      - name: date
        tests:
          - not_null

      - name: ticker
        tests:
          - not_null

      - name: daily_return
        description: "Simple daily return: (Price_t / Price_t-1) - 1."

  - name: i_cumulative
    description: >
      Cumulative return series computed from daily returns.
    columns:
      - name: date
        tests:
          - not_null

      - name: ticker
        tests:
          - not_null

      - name: cum_return
        description: "Cumulative return since start of series."

  - name: i_volatility
    description: >
      Realized volatility computed from daily returns.
      Rolling 30-day window and annualized.
    columns:
      - name: date
        tests:
          - not_null

      - name: ticker
        tests:
          - not_null

      - name: volatility
        description: "Annualized rolling volatility (30-day window)."

  - name: i_drawdown
    description: >
      Drawdown series computed from cumulative returns.
    columns:
      - name: date
        tests:
          - not_null

      - name: ticker
        tests:
          - not_null

      - name: drawdown
        description: "Peak-to-trough drawdown at each point in time."

  - name: i_sharpe
    description: >
      Period-aware Sharpe Ratio based on daily excess returns.
      Annualized using sqrt(252).
    columns:
      - name: date
        tests:
          - not_null

      - name: ticker
        tests:
          - not_null

      - name: sharpe_ratio
        description: "Annualized Sharpe Ratio."

  - name: i_cagr
    description: >
      Compound Annual Growth Rate calculated per ticker.
    columns:
      - name: ticker
        tests:
          - not_null
          - unique

      - name: cagr
        description: "Compound Annual Growth Rate."

  # -------------------------------------------------------
  # MART LAYER
  # -------------------------------------------------------
  - name: mart_prices
    description: >
      Final analytical mart consolidating prices, returns,
      risk metrics, and company metadata.
      Primary source for Streamlit dashboard and BI analysis.
    columns:
      - name: date
        tests:
          - not_null

      - name: ticker
        tests:
          - not_null

      - name: company_name
        description: "Company official name."

      - name: sector
        description: "GICS sector classification."

      - name: industry
        description: "GICS industry classification."

      - name: price
        description: "Adjusted closing price."

      - name: daily_return
        description: "Simple daily return."

      - name: cum_return
        description: "Cumulative return."

      - name: volatility
        description: "Annualized rolling volatility."

      - name: drawdown
        description: "Drawdown from historical peak."

      - name: sharpe_ratio
        description: "Annualized Sharpe Ratio."

      - name: cagr
        description: "Compound Annual Growth Rate."
